<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Login with Google Account</name>
   <tag></tag>
   <elementGuidId>7a2f0ff4-d851-41e2-b38c-7882ad216c74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.LoginButton_LoginButton__3qKtx > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>57fb9a21-fdde-4c12-8595-ed703385c6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login with Google Account</value>
      <webElementGuid>04f8c869-1962-4ca5-8fd4-3aad7c97ab80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;AuthPage_AuthPage__container__eW8TR&quot;]/div[@class=&quot;AuthPage_AuthPage__rightSection__1a-XY&quot;]/div[@class=&quot;AuthPage_AuthPage__rightSection__loginButton__zcEKA&quot;]/div[@class=&quot;LoginButton_LoginButton__3qKtx&quot;]/p[1]</value>
      <webElementGuid>94655dda-5556-432e-8f5d-23ac7ea040da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/p</value>
      <webElementGuid>30831712-5f47-447a-9199-4a2450a5bddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome aboard!'])[1]/following::p[2]</value>
      <webElementGuid>393512cc-7983-4989-ba6b-794eaa4425dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login with Google Account']/parent::*</value>
      <webElementGuid>d89fd42c-2c41-46e2-b2ff-e25c13f53b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>9bf5d23b-d088-4f50-9b90-21abbd376864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Login with Google Account' or . = 'Login with Google Account')]</value>
      <webElementGuid>1158b983-3596-4929-8786-6c3c4027ab3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
